In [1]:
import numpy as np

In [2]:
g = np.ones(4)
g = g.astype(int)

In [3]:
g**2

array([1, 1, 1, 1], dtype=int32)

In [4]:
q = np.array([[1,-2],[-2,3],[1,-3],[-1,4]])
q

array([[ 1, -2],
       [-2,  3],
       [ 1, -3],
       [-1,  4]])

In [5]:
np.sum(g[:,np.newaxis]*q,0)

array([-1,  2])

In [6]:
q

array([[ 1, -2],
       [-2,  3],
       [ 1, -3],
       [-1,  4]])

In [7]:
np.argmax(q,axis=1)

array([0, 1, 0, 1], dtype=int64)

In [10]:
q2 = np.reshape(q, (q.shape[0], -1))

In [12]:
q2.shape

(4, 2)